name = "Vilagust Modpack"
author = "Vilka & August"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d4b80bde72a4a22561e56af35ff1465db52acdd724d2d9884d09d217066ff84a"

[versions]
fabric = "0.16.10"
minecraft = "1.21.1"
