name = "Vilagust Modpack"
author = "Vilka & August"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cf3193e149dd7546ec458786f7591937e23c963ed67b0151fbe3e4798b1069b2"

[versions]
fabric = "0.16.10"
minecraft = "1.21.1"
