name = "Vilagust Modpack"
author = "Vilka & August"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d4f694b1cef1cf91056b624f0b52ece278c338b01c536816aee624685f56d1a2"

[versions]
fabric = "0.16.14"
minecraft = "1.21.5"

[options]
acceptable-game-versions = ["1.21.4"]
